### ISSUE TITLE
Possible to release the extension in open-vsx.org for codeoss based community?

### ISSUE THREAD

**Issue by larrycai** [10Nates/ollama-autocoder#1]
**Describe the bug**

Not a bug, more feature request to suggest to release this extension in https://open-vsx.org/ , since codeoss based opensource community like [vscodium](https://vscodium.com/) used to connect to that marketplace as well

**To Reproduce**
1. Go to ['open-vsx.org'](https://open-vsx.org/)
2. Search for 'ollama'
4. See 0 result(s)

**Expected behavior**

expect the `Ollama Autocoder` extension is there as well

**Screenshots**

<img width="887" alt="image" src="https://github.com/10Nates/ollama-autocoder/assets/106192/9ff22aaf-07c3-4b09-bfb1-1c98b84859c0">

**Desktop (please complete the following information):**

 - Browser [e.g. chrome, safari]: all browser, chrome

**Smartphone (please complete the following information):**

 - Browser [e.g. stock browser, safari]: all browser

**Additional context**

n/a

**Comment by 10Nates** [comment]
Resolved. Published on [open-vsx](https://open-vsx.org/extension/10nates/ollama-autocoder).
