### ISSUE TITLE
Any possibility we could add support for Intel Based MacBooks GPUs.

### ISSUE THREAD

**Issue by AiRC-ai** [10Nates/ollama-autocoder#10]
it would be great if we could add support for say my 5500m 8g on my i9.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 10Nates** [comment]
Unfortunately this is something I don't have a hand in. This is a feature that needs to be resolved with [Ollama](https://github.com/ollama/ollama). 

Honestly, I was under the impression that it was supported, so it's possible you don't have drivers or this is an issue with MacOS specifically. But I can't guarantee that.
