### ISSUE TITLE
Preview of autocomplete

### ISSUE THREAD

**Issue by quikssb** [10Nates/ollama-autocoder#2]
I would love this expansion to be able to preview suggestions, similar to GitHub Copilot Autocomplete.

**Comment by 10Nates** [comment]
How do you suppose it would work? The main problem with local LLMs tends to be speed, so the way this extension works works around that with the streaming system. If you have a good idea surrounding how this could be integrated with preview suggestions, I would love to hear it.

**Comment by 10Nates** [comment]
I have considered, and I will be adding a `response preview` option on by default in 0.0.5, which changes the label to the first line of the model's response, then halts the model unless it is triggered. I find this a good compromise.

![example](https://i.imgur.com/v4qoptx.png)

**Comment by 10Nates** [comment]
Added in [0.0.5](https://github.com/10Nates/ollama-autocoder/releases/tag/0.0.5)
