### ISSUE TITLE
Custom shortcut

### ISSUE THREAD

**Issue by Zacharieg** [10Nates/ollama-autocoder#3]
Hi !  

Thanks for this awesome VSCode plugin !

Is it possible to add a feature to choose a shortcut to generate code, and deactivate the space bar proposition ?

Thanks again for your work, have a good day !

**Comment by 10Nates** [comment]
For the shortcut, this is already possible. It is unbinded by default, but you can configure `@command:ollama-autocoder.autocomplete` in VS Code Keyboard Shortcuts. You can also activate it from the command palette without binding it.

Disabling the space bar seems like a simple settings addition that would help with the user experience, I will look into it.

**Comment by 10Nates** [comment]
Added in [0.0.5](https://github.com/10Nates/ollama-autocoder/releases/tag/0.0.5)
