### ISSUE TITLE
show error toasts

### ISSUE THREAD

**Issue by lakshaysethi** [10Nates/ollama-autocoder#9]
if extension tried to connect to ollama, but failed , display error in a toast , so lay users (like me)  can know what to do next / debug troubleshoot further

**Comment by 10Nates** [comment]
Which errors in particular do you expect to be shown, aside from connection errors?

**Comment by 10Nates** [comment]
Additional error toasts and clarification added in [v0.1.0](https://github.com/10Nates/ollama-autocoder/releases/tag/0.1.0)

Will leave this issue open for a few days for any additional error handling that I may have missed.
